/* Plugin structure generated by Schiavoni Pure Data external Generator */
#include "m_pd.h"
#include <math.h>
// ---------------------------------------------------
// Class definition
// ---------------------------------------------------
static t_class *rebit_class;

// ---------------------------------------------------
// Data structure definition
// ---------------------------------------------------
typedef struct _rebit {
   t_object x_obj;
   t_float bits;
   t_inlet * x_inlet_dsp_0;
   t_inlet * x_inlet_bits_float;
   t_outlet * x_outlet_dsp_0;

} t_rebit;

int32_t rebit_float2int(float f){
if (f >= 1.0) 
    return 2147483647; 
else if (f <= -1.0) 
    return -2147483648; 
else 
    return floor(f * 2147483648.0f);
}


float rebit_int2float(int32_t i){
   return i / 2147483648.0f;
}

// ---------------------------------------------------
// Functions signature
// ---------------------------------------------------
void * rebit_new(t_floatarg bits_arg);// Constructor
void rebit_destroy(t_rebit *x); //Destructor
static t_int * rebit_perform(t_int *w); //Perform function
static void rebit_dsp(t_rebit *x, t_signal **sp); //DSP function

// ---------------------------------------------------
// Perform
// ---------------------------------------------------
static t_int * rebit_perform(t_int *w){
   t_rebit *x = (t_rebit *)(w[1]);
   int n = (int)(w[2]);
   t_float *in1 = (t_float *)(w[3]);
   t_float *out1 = (t_float *)(w[4]);

   if (x->bits < 1) x->bits = 1;
   if (x->bits > 32) x->bits = 32;

   int i = 0;
   int j = 0;
   int32_t sample = 0;
	for(i = 0 ; i < n ; i++){
      sample = rebit_float2int(in1[i]); // convert sample from float 32 to int32
      for(j = 0 ; j < 32 - (int)x->bits ; j++){
         sample >>= 1; //Down size
      }
      for(j = 0 ; j < 32 - (int)x->bits ; j++){
         sample <<= 1; // Up size to scale back
      }
      out1[i] = rebit_int2float(sample); // convert it back to float 32
	}
   return (w + 5); // next block
}

// ---------------------------------------------------
// DSP Function
// ---------------------------------------------------
static void rebit_dsp(t_rebit *x, t_signal **sp){
   dsp_add(rebit_perform, 4, x, sp[0]->s_n, sp[0]->s_vec, sp[1]->s_vec);
}

// ---------------------------------------------------
// Constructor of the class
// ---------------------------------------------------
void * rebit_new(t_floatarg bits_arg){
   t_rebit *x = (t_rebit *) pd_new(rebit_class);

   x->bits = bits_arg;
   x->x_inlet_dsp_0 = inlet_new(&x->x_obj, &x->x_obj.ob_pd, &s_signal, &s_signal);
   x->x_outlet_dsp_0 = outlet_new(&x->x_obj, &s_signal);
   x->x_inlet_bits_float = floatinlet_new(&x->x_obj, &x->bits);

   return (void *) x;
}

// ---------------------------------------------------
// Destroy the class
// ---------------------------------------------------
void rebit_destroy(t_rebit *x) {
   post("You say good bye and I say hello");
   inlet_free(x->x_inlet_bits_float);
   inlet_free(x->x_inlet_dsp_0);

   outlet_free(x->x_outlet_dsp_0);

}

// ---------------------------------------------------
// Setup
// ---------------------------------------------------
void rebit_tilde_setup(void) {
   rebit_class = class_new(gensym("rebit~"),
      (t_newmethod) rebit_new, // Constructor
      (t_method) rebit_destroy, // Destructor
      sizeof (t_rebit),
      CLASS_NOINLET,
      A_DEFFLOAT,
      0);//Must always ends with a zero

   class_addmethod(rebit_class, (t_method) rebit_dsp, gensym("dsp"), 0);
}
// EOF---------------------------------------------------
